Add remote_podman CI
Add CI for remote_podman.

As part of working on this note that Carthage depends on git in its
plugin.

diff --git a/.github/workflows/build_and_release.yml b/.github/workflows/build_and_release.yml
--- a/.github/workflows/build_and_release.yml
+++ b/.github/workflows/build_and_release.yml
@@ -7,7 +7,7 @@ permissions:
   contents: read
   
 env:
-  core_dependencies: python3-requests python3-yaml python3-mako python3-sh python3-lmdb
+  core_dependencies: python3-requests python3-yaml python3-mako python3-sh python3-lmdb git
   run_tests: --carthage-config=build_test/authorized.yml -k "not no_rootless and not test_pki and not requires_podman_pod"
 jobs:
   build_python_dist:
@@ -88,12 +88,47 @@ jobs:
         podman run --rm debian:latest sleep 1 || true
         pytest-3 ${{env.run_tests}} tests
 
+  test_remote_podman:
+    runs-on: ubuntu-22.04
+    needs: build_python_dist
+    container:
+      image: 'debian:bookworm'
+      options: --privileged
+    env:
+      AWS_ACCESS_KEY: ${{secrets.AWS_ACCESS_KEY}}
+      AWS_SECRET_KEY: ${{secrets.AWS_SECRET_KEY}}
+
+    steps:
+    - name: Checkout code
+      uses: actions/checkout@v3
+
+    - name: download_dist
+      uses: actions/download-artifact@v3
+      with:
+        name: Python Distributions
+        path: dist
+
+    - name: install_dependencies_and_carthage
+      run: |
+        apt update
+        apt -y install python3 python3-pip python3-pytest git
+        pip3 install --break-system-packages dist/*whl
+        carthage --plugin carthage.podman --plugin https://github.com/hadron/carthage-aws generate_requirements >requirements.txt
+        pip3 install --break-system-packages -r requirements.txt
+        carthage --plugin carthage.podman --plugin https://github.com/hadron/carthage-aws install_dependencies
+
+    - name: Test Carthage
+      run: |
+        # It looks like podman create fails the first time with a resource busy
+        podman run --rm debian:latest sleep 1 || true
+        pytest-3 tests/test_podman.py --carthage-config=.github/aws.yml --remote-container-host -v -s --log-cli-level=info
+
   github_release:
     runs-on: ubuntu-22.04
     permissions:
       contents: write
     if: startsWith(github.ref, 'refs/tags/v')
-    needs: [build_python_dist, test_python_dist]
+    needs: [build_python_dist, test_python_dist, test_remote_podman]
     
     steps:
     - name: Checkout code
